version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.../
      # - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # - echo Finished the pre-build phase on `date`
      - echo test >> ping.txt
      - echo helloworld
    #   - sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
      # - echo $(kubectl version)
      - echo $(git version)
      # - echo $(helm version)
      # - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
      # - sudo chmod 700 get_helm.sh
      # - ./get_helm.sh
      # - echo $(helm version)
      # - git clone https://github.com/liuwei0915/test-parent-1.git
      # - echo $(git clone https://github.com/liuwei0915/test-parent-1.git)
      # - cd test-parent-1
      # - git submodule init
      - git submodule update --init --recursive
      - cd ..
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      # - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Build started on `date`

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # - echo Build started on `date`
      # - tail -2 ping.txt
      # - codebuild-breakpoint

